### PR TITLE
Respect web component default behavior

### LINKED ISSUE #18: Expecting same behavior of element counterparts
Why these stylings are necessary in layout constructors?

```java
public VerticalLayout() {
    getStyle().set("flexDirection", "column").set("width", "100%");
    setDefaultHorizontalComponentAlignment(Alignment.START);
}
```
and
```java
public HorizontalLayout() {
    getStyle().set("display", "inline-flex").set("flexDirection", "row");
    setDefaultVerticalComponentAlignment(Alignment.BASELINE);
}
```

I would expect the Flow components to behave like the custom elements, without the need to set properties explicitly. Also, they are difficult to override using CSS, since they are set on the element itself. Even for the 100% width, I would expect to be set in `vaadin-vertical-layout` element style (via `:host` selector), not here.

### PR DESCRIPTION
**Pull request by heruan**
Fixes #18.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/19)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/19#-L-69qab4A2nH8-a-rWv:-L-69qab4A2nH8-a-rWw:byj0sz5) (no related file):*
I opened discussion in the issue about whether we change these or not, blocking this for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/19)*

**Comment by pleku** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/19#-L-69qab4A2nH8-a-rWv:-L-6cjIItsS3XpganayL:bg7b35k) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I opened discussion in the issue about whether we change these or not, blocking this for now
</blockquote></details>

Should update the `vaadin-ordered-layout` webjar version to `1.0.0-alpha3`, I'll make a PR to `vaadin/flow` to get the webjars bom updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/19)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/19)*

**Comment by heruan** [comment]
With the latest commits to the web component repository, for both horizontal/vertical layouts a new container element was introduced to correctly scope spacing properties.

I guess before proceeding with this PR some design it's needed:

1. how to address the new container element? Existing method in `FlexLayout` won't work anymore.
2. is it worth to still extend `FlexLayout`, since the web component's host elements themselves are now just wrapper for the actual flex container?

Ref. https://github.com/vaadin/vaadin-ordered-layout/issues/14 and https://github.com/vaadin/vaadin-ordered-layout/issues/20

**Comment by heruan** [comment]
Maybe it's a long-shot, but in the latest commits I introduced a `FlexElement` interface with default methods to add the Flexbox API to any component.

This way, `FlexLayout` is a basic `div` with flex capabilities and `VerticalLayout`/`HorizontalLayout` can extends other superclass (i.e. `PolymerTemplate` and have its own property management (see https://github.com/vaadin/vaadin-ordered-layout/issues/25).

Don't know yet how to deal with private properties on the web component side. Comments and suggestions appreciated!

**Comment by heruan** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/19#-L-69qab4A2nH8-a-rWv:-L0QM6afiPGphEsxAzV_:bxg4ls1) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Should update the `vaadin-ordered-layout` webjar version to `1.0.0-alpha3`, I'll make a PR to `vaadin/flow` to get the webjars bom updated.
</blockquote></details>

With my last commit I've updated the PR to `vaadin-ordered-layout:master`, once `alpha4` is released we can remove the version override.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/19)*

**Comment by pleku** [comment]
Now there is an `alpha4` of the `vaadin-ordered-layout` and a soon a webjar too.

**Comment by heruan** [comment]
Rebased the PR on master. To sum up, this PR:

- introduces a mixin interface for flex layouts (`FlexComponent`);
- does not override any style in horizontal/vertical layouts, to be consistent with the web component.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/19#-:-L0e0-djfglqyTD2kJt3:bdai4kw)*

**Comment by heruan** [comment]
Any comment on this?

The only breaking change is for those who had used `FlexComponent` constants which here are package scoped (since there's an API to set the corresponding attributes, feels like an anti-pattern to set them manually).

Other than that, this let any component to implement an interface to acquire the Flex API and does not break existing classes already extending `FlexComponent`.

Plus, a couple of missing JavaDoc and enum values that were missing.

**Comment by ZheSun88** [comment]
@heruan I am going to merge this PR (finally), and we are going to do the rest of the work (if it is needed). It would be better that you can point out the missing parts... I will add it now..

**Comment by heruan** [comment]
Thank you @ZheSun88 for the feedback; I don't think there are missing parts, it's just a refactoring so tests should be okay. Maybe we can add documentation about the `FlexComponent` mixin interface?

**Comment by heruan** [comment]
I guess it's better to add the tutorial along the others in the Flow repository. Okay to merge for me.

**Comment by ZheSun88** [comment]
Reviewed 10 of 14 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/19)*

**Pull request merged**
