### PR TITLE
Add margin and padding api to VerticalLayout and HorizontalLayout.

### LINKED ISSUE #1: Vertical and HorizontalLayout are missing spacing & padding API
@tmattsso commented on [Wed Sep 20 2017](https://github.com/vaadin/flow/issues/2448)

The margin API is quite convenient in many cases where the developer just wants a margin and nothing else; having a stylesheet is usually overkill.

---

@pleku commented on [Sat Sep 23 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331630229)

@jouni should this be somehow in Valo2 for `vaadin-vertical-layout` and `vaadin-horizontal-layout` or ? I don't see us just building an API for this on the server side that would be something that the user cannot tweak from their App Theme.

---

@jouni commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331811053)

We have talked about this with the UX team. Not sure how, but I think we need to provide this, still. It would be great to have something like `setMargin(Margin.MEDIUM)`, where `Margin` is an enum of possible values. Same for spacing.

So, I’m expecting these to appear in the web component first, then we can create the corresponding server API.

---

@jouni commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331811126)

I’ll open a new issue in the web component layout repo.

---

@jouni commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331812619)

https://github.com/vaadin/vaadin-ordered-layout/issues/3

---

@Legioth commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2448#issuecomment-331858271)

The same also applies for spacing. Should there be a separate ticket about that in this repository, or can we do both with this single ticket?

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #1 

The build will not fail after https://github.com/vaadin/flow/pull/3300 is merged and a new snapshot is published.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/35)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java, line 140 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-L2d1GS30sYehuFDiykJ:-L2d1GS30sYehuFDiykK:b-5dfgm5) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/831574173371548affb436469d3a3adfc20bf057/src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java#L140)):*
> public void setMargin(boolean margin) {
>         getThemeList().set("margin", margin);
>     }

Does it make sense to extract common parts of V/H layouts into a separate class or interface (with default impls) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java, line 140 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-L2d1GS30sYehuFDiykJ:-L2dJmHlogCLJaVQO2fo:b-kc0v9p) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/831574173371548affb436469d3a3adfc20bf057/src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java#L140)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public void setMargin(boolean margin) {
>         getThemeList().set("margin", margin);
>     }

Does it make sense to extract common parts of V/H layouts into a separate class or interface (with default impls) ?
</blockquote></details>

It cannot be an interface because each method needs `getThemeList` and that one requires `getElement` from `Component`class, so I've created an abstract class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35)*

**Comment by heruan** [comment]
I'm not getting either why `ThemeableComponent` can't be a mixin interface, like:

```java
public interface ThemableComponent extends HasElement {
    
    default void setMargin(boolean margin) {
        getThemeList().set("margin", margin);
    }

    default void setPadding(boolean padding) {
        getThemeList().set("padding", padding);
    }

    default ThemeList getThemeList() {
        return getElement().getThemeList();
    }
}
```

**Comment by SomeoneToIgnore** [comment]
> HasElement

Had forgotten about it, sure it can be, fixed.

> Plus, shouldn't this be placed on Flow's repo rather than this?

Most probably it should, but the ticket does not say anything about it, that's why it was not added.
@pleku , what are the plans for theming, should this interface exist as common api?

---

Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-:-L2doq2QiWQBBiAbXVWW:b-sw7ag7)*

**Comment by SomeoneToIgnore** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java, line 140 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-L2d1GS30sYehuFDiykJ:-L2dpL8FI_V3hUaBEtGb:b-qaxy9k) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/831574173371548affb436469d3a3adfc20bf057/src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java#L140)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

It cannot be an interface because each method needs `getThemeList` and that one requires `getElement` from `Component`class, so I've created an abstract class.
</blockquote></details>

As pointed above, it can, changed to interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35)*

**Comment by heruan** [comment]
From my perspective I'd expect `ThemeList` and `ThemableComponent` to be in the same repo (not this layout-specific one), but maybe the `setMargin`/`setPadding` methods should be layout-specific (hence place in `FlexComponent` mixin)?

**Comment by SomeoneToIgnore** [comment]
>  the setMargin/setPadding methods should be layout-specific 

That's the reason I'm reluctant to include `ThemableComponent` into `flow-server`: it has only one method and it is already in `flow-server` lowlevel API.
Should I remove the class into `ThemableLayout` instead so it won't confuse anyone?

> `FlexComponent`

Not sure if it should belong there, since these methods do not make sense for `FlexLayout` that is also using this mixin.

---

Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-:-L2dqdA5wRaXfW9vhuN3:bvq8xt8)*

**Comment by SomeoneToIgnore** [comment]
s/remove/rename/

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-:-L2drmnANm6i7hTZHMU-:bjo69mv)*

**Comment by SomeoneToIgnore** [comment]
Sorry, that message came rather abrupt.
If I put it this way:

`ThemableComponent` has three methods, one is already in `flow-server` (`getThemeList`), two others (margin and padding) are relevant to vertical and horizontal layouts only.

Which means that
* we cannot put those two methods (margin and padding) into `FlexComponent` since `FlexLayout`will have them also and those are not applicable to it
* it does not make sense to put `ThemableComponent` in `flow-server` because the only common method is already there

So, it seems to me that he only viable thing to do now is to rename `ThemableComponent` into `ThemableLayout` so it won't confuse the users.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-:-L2ds5XLAYbMKoLVDB-K:b-il8cyh)*

**Comment by heruan** [comment]
> it does not make sense to put `ThemableComponent` in `flow-server` because the only common method is already there

It is? I maybe not up-to-date with the latest commit, but I've seen the `getThemeList` being added to the Element API, not to the Component API (e.g. mixin interface).

**Comment by pleku** [comment]
As of now we will only have `padding` and `margin` only for `HorizontalLayout` and `VerticalLayout`. Nothing else planned for V10. Let's not put those to `Flow` as they are really layout web components theming features.

If / when we do more layouts later, things might change, but I currently see no reasons to do it even if we would later on add more layouts based on web components. 

Otherwise, `ThemableComponent` is a really bad name for something that has `padding` and `margin`. The `theme` attribute can contain lots of other things, and is totally web component specific.

My goal is that at some point we can generate the `theme` attribute variants for each web component. But that is not for V10.

---

Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-:-L2e11WS6K5hcepizqTj:bmig0mq)*

**Comment by pleku** [comment]
Considering also about changing the `ThemableComponent` to `HasTheme` and only having the `getThemeList()` interface as a mixin in Flow, but the naming would be in conflict with the `Theme` annotation that we are adding currently. Also IMO `HasComponentTheme` doesn't really for the same reason.

But I do agree that e.g. `Button` could have the `getThemeList()` method. Again. `getTheme()` would be confusing to with the `Theme` annotation.

---

Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-:-L2e2WgBsdB6ttSIRT4v:b-btt128)*

**Comment by heruan** [comment]
Completely agree about the `margin`/`padding` API to be layout-specific.

> But I do agree that e.g. `Button` could have the `getThemeList()` method.

I really hope this will be in V10, as a `HasTheme` mixin, as all Vaadin components have many themeable features. And since AFAIK there's ongoing work about themes right now maybe it's a good time to close the circle!

**Comment by pleku** [comment]
>I really hope this will be in V10, as a HasTheme mixin, as all Vaadin components have many themeable features. And since AFAIK there's ongoing work about themes right now maybe it's a good time to close the circle

Again, the naming might not be `HasTheme`, but actually something like that could be automatically created for those web components that actually have themes.

Anyways, it is not a part of this issue or PR.

**Comment by SomeoneToIgnore** [comment]
Alright, so now I'll just rename the `ThemableComponent` interface to `ThemableLayout` interface and leave it as is in the PR.
Let's create a new mixin in a separate PR and include it here later, if needed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35#-:-L2e7mHntobeRpnBGIFi:bxukg16)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/35)*

**Pull request merged**
