### PR TITLE
Fix layout defaults to match V8

### PR DESCRIPTION
**Pull request by pleku**
Made defaults for padding & spacing match the same as in V8.
Though now padding is on by default instead of margin, since in V8 margin
actually meant padding in css, even though in Java it was named as margin.

Slightly related to #45

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/47)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/orderedlayout/HorizontalLayout.java, line 38 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/47#-L8BWl160lE-pv3mke5z:-L8BWl160lE-pv3mke6-:b-anm24f) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/fc28373cf63cee0a64dad4016ee33c9c387bbadb/src/main/java/com/vaadin/flow/component/orderedlayout/HorizontalLayout.java#L38)):*
> public HorizontalLayout() {
>         setSpacing(true);
>     }

Should there be a `HorizontalLayout(boolean spacing)` as a main CTOR which is used by the default CTOR for delegation.

Otherwise if I don't want spacing then I need to instantiate using `HorizontalLayout()`  and then unset spacing..... It's a bit longer than `HorizontalLayout(false)`

---

*[src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java, line 38 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/47#-L8BXBBn2eVU5ggqhLmB:-L8BXBBn2eVU5ggqhLmC:b-ftwaoh) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/fc28373cf63cee0a64dad4016ee33c9c387bbadb/src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java#L38)):*
> public VerticalLayout() {
>         setSpacing(true);
>         setPadding(true);
>     }

Same question here about main CTOR (with two parameters here may be) as for `HorizontalLayout`.

---

*[src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java, line 117 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/47#-L8BXlG6-GZFLzYgIWve:-L8BXlG6-GZFLzYgIWvf:b-m4u4kf) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/4ddef797f823429fd68034c00aea4286f5e61a60/src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java#L117)):*
> Div themeSettings = new Div(
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>                 new Label("Current theme supports 'spacing': "),
>                 createToggleThemeButton(layout, "spacing-xs"),
>                 createToggleThemeButton(layout, "spacing-s"),
>                 createToggleThemeButton(layout, "spacing", layout::setSpacing),
>                 createToggleThemeButton(layout, "spacing-l"),
>                 createToggleThemeButton(layout, "spacing-xl"));
</details>

completely removed ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/47)*

**Comment by pleku** [comment]
Review status: 2 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/orderedlayout/HorizontalLayout.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/47#-L8BWl160lE-pv3mke5z:-L8BboLAl1_cehCDSd8i:b-rjr7lg) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/fc28373cf63cee0a64dad4016ee33c9c387bbadb/src/main/java/com/vaadin/flow/component/orderedlayout/HorizontalLayout.java#L38)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public HorizontalLayout() {
>         setSpacing(true);
>     }

Should there be a `HorizontalLayout(boolean spacing)` as a main CTOR which is used by the default CTOR for delegation.

Otherwise if I don't want spacing then I need to instantiate using `HorizontalLayout()`  and then unset spacing..... It's a bit longer than `HorizontalLayout(false)`
</blockquote></details>

I don't see that we should provide convenience constructors to modify all default values.

Spacing enabled by default has been proven to be what most users want. We don't have a convenience constructor in the older Vaadin versions, so I'm pretty content about not adding one now https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/HorizontalLayout.java

---

*[src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/47#-L8BXBBn2eVU5ggqhLmB:-L8Bc5Mer_ZbfKWqeKC3:bka1vaw) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/fc28373cf63cee0a64dad4016ee33c9c387bbadb/src/main/java/com/vaadin/flow/component/orderedlayout/VerticalLayout.java#L38)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public VerticalLayout() {
>         setSpacing(true);
>         setPadding(true);
>     }

Same question here about main CTOR (with two parameters here may be) as for `HorizontalLayout`.
</blockquote></details>

Same answer as with HorizontalLayout. https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/VerticalLayout.java#L36

---

*[src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java, line 117 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/47#-L8BXlG6-GZFLzYgIWve:-L8BbXpo5WOtGocKTInK:b-t5owe1) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/4ddef797f823429fd68034c00aea4286f5e61a60/src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java#L117)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Div themeSettings = new Div(
>                 new Label("Current theme supports 'spacing': "),
>                 createToggleThemeButton(layout, "spacing-xs"),
>                 createToggleThemeButton(layout, "spacing-s"),
>                 createToggleThemeButton(layout, "spacing", layout::setSpacing),
>                 createToggleThemeButton(layout, "spacing-l"),
>                 createToggleThemeButton(layout, "spacing-xl"));

completely removed ?
</blockquote></details>

Yeah, they have no place in a demo IMO.

I added back as a separate IT test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/47)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 7 of 8 files at r2.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/47#-:-L8BdfwoQqDmASPqwfiw:bnfp4nl)*

**Comment by caalador** [comment]
Reviewed 2 of 7 files at r1, 8 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/47)*

**Pull request merged**
