### PR TITLE
Add FlexLayout API. (#80)

### LINKED ISSUE #80: FlexLayout is missing some properties
As a user when using the FlexLayout I want to have access to the whole flexbox API.
Currently missing:
- flex-shrink
- order
- flex-direction
- align-content
- flex-basis

### PR DESCRIPTION
**Pull request by sahalsaad**
Fixes #80

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/97)

### CODE REVIEW

**Comment by mehdi-vaadin** [comment]
@sahalsaad  Thank you very much for your contribution. We will review your work as soon as possible.

**Comment by sahalsaad** [comment]
Very hard for me to add integration test since I don't have the license. I just added unit test instead.

**Comment by sahalsaad** [comment]
@mehdi-vaadin

**Comment by sahalsaad** [comment]
Done @pleku :+1:

**Comment by sahalsaad** [comment]
@pleku Done.

**Pull request merged**
