### PR TITLE
Combine demo views for horizontal- and verticallayout to orderedlayout

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/43)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/43#-L5NdQR--40i-G8AoVAs:-L5NdQR--40i-G8AoVAt:b-1zm3d7) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/59bdde4ac9c19dd0d75f83bc6283dbaac7b70fec/src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java#L34)):*
> ```Java
> 
>     @Override
>     protected void initView() {
> ```

Wouldn't it be better to have a single method on the Horizontal/VerticalLayoutView that calls all those methods internally? Something like `HorizontalLayoutView.createDemos(this);`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/43)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/43#-L5NdGRTwOfpStGMtbdv:-L5NdGRTwOfpStGMtbdw:bnxn708) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/59bdde4ac9c19dd0d75f83bc6283dbaac7b70fec/src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java#L47)):*
>  HorizontalLayoutView.createDefaultLayout(this);
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>         HorizontalLayoutView.createLayoutWithSpacing(this);
>         HorizontalLayoutView.createLayoutWithDefaultAlignment(this);
>         HorizontalLayoutView.createLayoutWithIndividualAlignments(this);
>         HorizontalLayoutView.createLayoutWithExpandRatios(this);
>         HorizontalLayoutView.createLayoutWithCenterComponent(this);
</details>
>  
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>         VerticalLayoutView.createDefaultLayout(this);
>         VerticalLayoutView.createLayoutWithSpacing(this);
>         VerticalLayoutView.createLayoutWithDefaultAlignment(this);
>         VerticalLayoutView.createLayoutWithIndividualAlignments(this);
>         VerticalLayoutView.createLayoutWithExpandRatios(this);
>         VerticalLayoutView.createLayoutWithCenterComponent(this);
</details>


I would recommend avoid `static`  methods. Even though it's just a demo.

What could be done: 
- Create `AbstractOrderLayoutViewFactory` (interface or class whatever and whatever name).
- Put all those static methods in this type.
- Have to implementations of this class  : for vertical and horizontal layout (may be with reusable code in the `AbstractOrderLayoutViewFactory`).
- Instantiate those two classes and go through them via a cycle referring to them as `AbstractOrderLayoutViewFactory`. 
- Polymorphism will do its work.

I think the code will be better an cleaner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/43)*

**Comment by caalador** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/43#-L5NdQR--40i-G8AoVAs:-L5O2Ckttd0ft0R7LQAN:begbjih) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/59bdde4ac9c19dd0d75f83bc6283dbaac7b70fec/src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java#L34)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Wouldn't it be better to have a single method on the Horizontal/VerticalLayoutView that calls all those methods internally? Something like `HorizontalLayoutView.createDemos(this);`.
</blockquote></details>

DemoView collectSources eats away possibilities.

---

*[src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/43#-L5NdGRTwOfpStGMtbdv:-L5NtrE0rqEg3bA1aMGQ:bazy6xl) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/59bdde4ac9c19dd0d75f83bc6283dbaac7b70fec/src/test/java/com/vaadin/flow/component/orderedlayout/demo/OrderedLayoutView.java#L47)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  HorizontalLayoutView.createDefaultLayout(this);
>         HorizontalLayoutView.createLayoutWithSpacing(this);
>         HorizontalLayoutView.createLayoutWithDefaultAlignment(this);
>         HorizontalLayoutView.createLayoutWithIndividualAlignments(this);
>         HorizontalLayoutView.createLayoutWithExpandRatios(this);
>         HorizontalLayoutView.createLayoutWithCenterComponent(this);
>  
>         VerticalLayoutView.createDefaultLayout(this);
>         VerticalLayoutView.createLayoutWithSpacing(this);
>         VerticalLayoutView.createLayoutWithDefaultAlignment(this);
>         VerticalLayoutView.createLayoutWithIndividualAlignments(this);
>         VerticalLayoutView.createLayoutWithExpandRatios(this);
>         VerticalLayoutView.createLayoutWithCenterComponent(this);


I would recommend avoid `static`  methods. Even though it's just a demo.

What could be done: 
- Create `AbstractOrderLayoutViewFactory` (interface or class whatever and whatever name).
- Put all those static methods in this type.
- Have to implementations of this class  : for vertical and horizontal layout (may be with reusable code in the `AbstractOrderLayoutViewFactory`).
- Instantiate those two classes and go through them via a cycle referring to them as `AbstractOrderLayoutViewFactory`. 
- Polymorphism will do its work.

I think the code will be better an cleaner.

</blockquote></details>

I was going to unify the methods as they are basically the same, but then the source code shown on the demo page would be wrong. also DemoView source collection is what it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/43)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/43#-:-L5OAi8H_woEmGrTEs4B:bnfp4nl)*

**Pull request merged**
