### PR TITLE
Fix default spacing applied to layouts.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ordered-layout-flow/38)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/orderedlayout/ThemableLayout.java, line 95 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/38#-L3cerSHjMOGpJlXMhKz:-L3cerSHjMOGpJlXMhL-:b-sl28i1) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/e0e7a8f0c7c819a46883e604bd5d1240df3e8eed/src/main/java/com/vaadin/flow/component/orderedlayout/ThemableLayout.java#L95)):*
> ```Java
>      */
>     default boolean hasSpacing() {
>         return getThemeList().contains("spacing");
> ```

I'm intrigued about what the API should return when `spacing-*` is applied. Feels like it should return `true`, but I don't know the decisions behind this design choice. Do you have any idea?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/38)*

**Comment by SomeoneToIgnore** [comment]
*[src/main/java/com/vaadin/flow/component/orderedlayout/ThemableLayout.java, line 95 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/38#-L3cerSHjMOGpJlXMhKz:-L3cfpKscj5VIIh_A__o:b-8ullfc) ([raw file](https://github.com/vaadin/vaadin-ordered-layout-flow/blob/e0e7a8f0c7c819a46883e604bd5d1240df3e8eed/src/main/java/com/vaadin/flow/component/orderedlayout/ThemableLayout.java#L95)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I'm intrigued about what the API should return when `spacing-*` is applied. Feels like it should return `true`, but I don't know the decisions behind this design choice. Do you have any idea?
</blockquote></details>

It returns `false`.

I've raised a similar question about having multiple themes at once: https://github.com/vaadin/vaadin-ordered-layout-flow/issues/34#issuecomment-359786412

From what I've got the decision is to treat them as different styles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/38)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/38)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ordered-layout-flow/38#-:-L3ciClT1dSqalidCDgH:bnfp4nl)*

**Pull request merged**
